#
# Created by mkmk, DO NOT EDIT!!!
#
CC=arm-none-eabi-gcc
LD=arm-none-eabi-gcc
#
DE=-DSYSVER_U=5 -DSYSVER_L=4 -DSYSVER_T=PG180222A -DSIZE_OF_AWORD=4 -DSIZE_OF_SINT=4 -DBOARD_CC1350_LAUNCHXL -DBOARD_TYPE=CC1350_LAUNCHXL -D__CC13XX__ -D__cc1350__ 
#
IN= -I . -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL -I /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel -I /home/ls/Desktop/OLSONET/PICOS/PicOS -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/RF -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage -I /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI -I /home/ls/Desktop/OLSONET/PICOS/PicOS/VLibs/PlugNull
#
all :	Image
#
# target: ""
Image :	KTMP/app.o KTMP/main.o KTMP/kernel.o KTMP/tcv.o KTMP/startup_gcc.o KTMP/ccfg.o KTMP/sensors.o KTMP/analog_sensor.o KTMP/pin_sensor.o KTMP/pins_sys.o KTMP/buttons.o KTMP/storage_mx25r8035.o KTMP/ser_out.o KTMP/ser_outb.o KTMP/ser_in.o KTMP/ser_select.o KTMP/form.o KTMP/scan.o KTMP/ser_outf.o KTMP/ser_inf.o KTMP/rfprop.o KTMP/plug_null.o KTMP/__outserial.o KTMP/__inserial.o KTMP/vform.o KTMP/vscan.o KTMP/smartrf_settings_lp_hr.o 
	$(LD) -Wl,-T,/home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cc13x0f128.lds -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -mthumb -Wl,-Map,Image.map -Wl,--gc-sections -nostartfiles -static -o Image KTMP/app.o KTMP/main.o KTMP/kernel.o KTMP/tcv.o KTMP/startup_gcc.o KTMP/ccfg.o KTMP/sensors.o KTMP/analog_sensor.o KTMP/pin_sensor.o KTMP/pins_sys.o KTMP/buttons.o KTMP/storage_mx25r8035.o KTMP/ser_out.o KTMP/ser_outb.o KTMP/ser_in.o KTMP/ser_select.o KTMP/form.o KTMP/scan.o KTMP/ser_outf.o KTMP/ser_inf.o KTMP/rfprop.o KTMP/plug_null.o KTMP/__outserial.o KTMP/__inserial.o KTMP/vform.o KTMP/vscan.o KTMP/smartrf_settings_lp_hr.o /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE/driverlib/bin/gcc/driverlib.lib
	arm-none-eabi-size -Ax Image
	cp Image Image.out
	
	arm-none-eabi-objcopy Image -O ihex Image.hex
	arm-none-eabi-objdump -D -S Image.out > Image.objdump

KTMP/app.o : app.cc /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/serf.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/phys_cc1350.h /home/ls/Desktop/OLSONET/PICOS/PicOS/VLibs/PlugNull/plug_null.h
	mkdir -p KTMP
	cp app.cc KTMP/___pcs___app.c
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -E KTMP/___pcs___app.c  > KTMP/___pct___app.c
	picomp -p < KTMP/___pct___app.c > KTMP/app.c
	rm KTMP/___pcs___app.c KTMP/___pct___app.c
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c KTMP/app.c -o KTMP/app.o 

KTMP/main.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/main.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage_mx25r8035.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_storage.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/irq_timer_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/irq_timer.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/irq_buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/irq_pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins_interrupts.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/scheduler.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/main.c -o KTMP/main.o 

KTMP/kernel.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.c -o KTMP/kernel.o 

KTMP/tcv.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcvphys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcvplug.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_node_data.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv.c -o KTMP/tcv.o 

KTMP/startup_gcc.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/startup_gcc.c
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/startup_gcc.c -o KTMP/startup_gcc.o 

KTMP/ccfg.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/ccfg.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/RF/rfleds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cc1350.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/ccfg.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/ccfg.c -o KTMP/ccfg.o 

KTMP/sensors.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.c -o KTMP/sensors.o 

KTMP/analog_sensor.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.c -o KTMP/analog_sensor.o 

KTMP/pin_sensor.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys_in.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.c -o KTMP/pin_sensor.o 

KTMP/pins_sys.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.c -o KTMP/pins_sys.o 

KTMP/buttons.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.c -o KTMP/buttons.o 

KTMP/storage_mx25r8035.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage_mx25r8035.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage_mx25r8035.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_storage.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage_eeprom.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Storage/storage_mx25r8035.c -o KTMP/storage_mx25r8035.o 

KTMP/ser_out.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_out.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_out.c -o KTMP/ser_out.o 

KTMP/ser_outb.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_outb.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_outb.c -o KTMP/ser_outb.o 

KTMP/ser_in.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_in.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_in.c -o KTMP/ser_in.o 

KTMP/ser_select.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_select.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_select.c -o KTMP/ser_select.o 

KTMP/form.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.c -o KTMP/form.o 

KTMP/scan.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/scan.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/scan.c -o KTMP/scan.o 

KTMP/ser_outf.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_outf.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_outf.c -o KTMP/ser_outf.o 

KTMP/ser_inf.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_inf.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ser_inf.c -o KTMP/ser_inf.o 

KTMP/rfprop.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/rfprop.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcvphys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/RF/rfleds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cc1350.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/smartrf_settings.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/rfprop.c -o KTMP/rfprop.o 

KTMP/plug_null.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/VLibs/PlugNull/plug_null.cc /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcvplug.h
	mkdir -p KTMP
	cp /home/ls/Desktop/OLSONET/PICOS/PicOS/VLibs/PlugNull/plug_null.cc KTMP/___pcs___plug_null.c
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -E KTMP/___pcs___plug_null.c  > KTMP/___pct___plug_null.c
	picomp -p < KTMP/___pct___plug_null.c > KTMP/plug_null.c
	rm KTMP/___pcs___plug_null.c KTMP/___pct___plug_null.c
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c KTMP/plug_null.c -o KTMP/plug_null.o 

KTMP/__outserial.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/__outserial.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/__outserial.c -o KTMP/__outserial.o 

KTMP/__inserial.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/__inserial.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/__inserial.c -o KTMP/__inserial.o 

KTMP/vform.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/vform.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/vform.c -o KTMP/vform.o 

KTMP/vscan.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/vscan.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/form.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/vscan.c -o KTMP/vscan.o 

KTMP/smartrf_settings_lp_hr.o : /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/smartrf_settings_lp_hr.c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_options.sys /home/ls/Desktop/OLSONET/PICOS/PicOS/modsyms.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portnames.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cmsis_gcc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/arch.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/mach.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/uart_def.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/sysio.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/portmap.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/sensors_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/sensors.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/analog_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/pins_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Sensors/pin_sensor.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/pins.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/buttons_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/buttons.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/IO/leds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/diag_sys.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Misc/dbgtrc.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/BOARDS/CC1350_LAUNCHXL/board_headers.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/VNetI/tcv_defs.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/ualeds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/Serial/uart.h /home/ls/Desktop/OLSONET/PICOS/PicOS/kernel/kernel.h /home/ls/Desktop/OLSONET/PICOS/PicOS/PLibs/RF/rfleds.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/cc1350.h /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/smartrf_settings.h
	mkdir -p KTMP
	$(CC) -Dgcc -D__CC1350__ -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -specs="nosys.specs" -fno-strict-aliasing -std=c99 --asm -fmax-errors=10 -I /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/CC13XXWARE $(DE) $(IN) -c /home/ls/Desktop/OLSONET/PICOS/PicOS/CC13XX/smartrf_settings_lp_hr.c -o KTMP/smartrf_settings_lp_hr.o 


clean :
	rm -rf KTMP
